/* This file is automatically generated. Don't try to edit it by hand! */
import UIKit

/// Helper class for finding the proper bundle
private class ImageBundleHelper {}

/// Images contained within the asset catalog
public enum ImageAsset: String, CaseIterable {
    case durian
    case matterhorn
    case prayer_wheel
    case ross_lake
    case warsaw
}

public extension UIImage {
    convenience init(from imageAsset: ImageAsset) {
        self.init(named: imageAsset.rawValue,
                  in: Bundle(for: ImageBundleHelper.self),
                  compatibleWith: nil)!
    }

    static let prr_durian = UIImage(from: .durian)

    static let prr_matterhorn = UIImage(from: .matterhorn)

    static let prr_prayer_wheel = UIImage(from: .prayer_wheel)

    static let prr_ross_lake = UIImage(from: .ross_lake)

    static let prr_warsaw = UIImage(from: .warsaw)
}
